# Generated by Django 2.1.7 on 2019-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='free_agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekeffective', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='hall_of_fame_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonname', models.CharField(default='Not Specified', max_length=30)),
                ('championteamname', models.CharField(default='Not Specified', max_length=50)),
                ('championcoachname', models.CharField(default='Not Specified', max_length=50)),
                ('champlogo', models.ImageField(blank=True, null=True, upload_to='champlogos')),
                ('runnerupteamname', models.CharField(default='Not Specified', max_length=50)),
                ('runnerupcoachname', models.CharField(default='Not Specified', max_length=50)),
                ('championshipreplay', models.CharField(default='Not Specified', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hall_of_fame_roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['pokemon__pokemon'],
            },
        ),
        migrations.CreateModel(
            name='rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(default='No rules announced')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=15)),
                ('team1score', models.IntegerField(default=0)),
                ('team2score', models.IntegerField(default=0)),
                ('replay', models.CharField(default='Link', max_length=100)),
                ('team1usedz', models.BooleanField(default=False)),
                ('team2usedz', models.BooleanField(default=False)),
                ('team1megaevolved', models.BooleanField(default=False)),
                ('team2megaevolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='trade_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekeffective', models.IntegerField(default=1)),
            ],
        ),
    ]
