# Generated by Django 2.1.7 on 2019-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='replay',
            field=models.CharField(default='Link', max_length=100),
        ),
    ]
