# Generated by Django 2.1.7 on 2019-05-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('pokemondatabase', '0001_initial'),
        ('individualleague', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='addedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeadded', to='pokemondatabase.all_pokemon'),
        ),
        migrations.AddField(
            model_name='trading',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.coachdata'),
        ),
        migrations.AddField(
            model_name='trading',
            name='droppedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedropped', to='pokemondatabase.all_pokemon'),
        ),
        migrations.AddField(
            model_name='trading',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.seasonsetting'),
        ),
        migrations.AddField(
            model_name='trade_request',
            name='offeredpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedroppedrequest', to='leagues.roster'),
        ),
        migrations.AddField(
            model_name='trade_request',
            name='requestedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeaddedrequest', to='leagues.roster'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.seasonsetting'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='leagues.coachdata'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='leagues.coachdata'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='leagues.coachdata'),
        ),
        migrations.AddField(
            model_name='rule',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.seasonsetting'),
        ),
        migrations.AddField(
            model_name='hall_of_fame_roster',
            name='hall_of_frame_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hofentries', to='individualleague.hall_of_fame_entry'),
        ),
        migrations.AddField(
            model_name='hall_of_fame_roster',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon'),
        ),
        migrations.AddField(
            model_name='hall_of_fame_entry',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
        migrations.AddField(
            model_name='free_agency',
            name='addedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added', to='pokemondatabase.all_pokemon'),
        ),
        migrations.AddField(
            model_name='free_agency',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.coachdata'),
        ),
        migrations.AddField(
            model_name='free_agency',
            name='droppedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped', to='pokemondatabase.all_pokemon'),
        ),
        migrations.AddField(
            model_name='free_agency',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.seasonsetting'),
        ),
    ]
