# Generated by Django 2.1.7 on 2019-05-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0002_auto_20190506_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.CharField(max_length=15),
        ),
    ]
