# Generated by Django 2.1.7 on 2019-06-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0002_auto_20190531_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_agency',
            name='weekeffective',
        ),
        migrations.RemoveField(
            model_name='trading',
            name='weekeffective',
        ),
        migrations.AddField(
            model_name='free_agency',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='free_agency',
            name='timeadded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trading',
            name='timeadded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
