# Generated by Django 2.1.7 on 2019-06-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0003_auto_20190602_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_agency',
            name='timeadded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trading',
            name='timeadded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
