# Generated by Django 2.1.7 on 2019-05-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_draft_pickstart'),
        ('individualleague', '0003_auto_20190506_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.seasonsetting')),
            ],
        ),
    ]
