# Generated by Django 2.1.7 on 2019-05-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0004_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rules',
            field=models.TextField(default='No rules announced'),
        ),
    ]
