# Generated by Django 2.1.7 on 2019-06-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0002_auto_20190614_2224'),
        ('leagues', '0006_auto_20190617_1941'),
        ('individualleague', '0004_auto_20190602_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='left_pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backuppick', to='pokemondatabase.all_pokemon')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.coachdata')),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftpick', to='pokemondatabase.all_pokemon')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.seasonsetting')),
            ],
        ),
    ]
