# Generated by Django 2.1.7 on 2019-06-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0005_left_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
