# Generated by Django 2.1.7 on 2019-05-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0006_free_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_agency',
            name='addedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added', to='pokemondatabase.all_pokemon'),
        ),
    ]
