# Generated by Django 2.1.7 on 2019-06-26 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0021_draft_skipped'),
        ('individualleague', '0006_schedule_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='playoff_match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playoffround', models.CharField(max_length=15)),
                ('team1score', models.IntegerField(default=0)),
                ('team2score', models.IntegerField(default=0)),
                ('replay', models.CharField(default='Link', max_length=100)),
                ('team1usedz', models.BooleanField(default=False)),
                ('team2usedz', models.BooleanField(default=False)),
                ('team1megaevolved', models.BooleanField(default=False)),
                ('team2megaevolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.seasonsetting')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoffteam1', to='leagues.coachdata')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoffteam2', to='leagues.coachdata')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoffwinner', to='leagues.coachdata')),
            ],
        ),
    ]
