# Generated by Django 2.1.7 on 2019-05-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0031_seasonsetting_drafttimer'),
        ('individualleague', '0007_auto_20190517_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='trade_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedpokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeadded', to='leagues.roster')),
                ('droppedpokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedropped', to='leagues.roster')),
            ],
        ),
    ]
