# Generated by Django 2.1.7 on 2019-06-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0007_playoff_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.CharField(max_length=30),
        ),
    ]
