# Generated by Django 2.1.7 on 2019-05-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0009_auto_20190517_2045'),
        ('leagues', '0031_seasonsetting_drafttimer'),
        ('individualleague', '0008_trade_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekeffective', models.IntegerField(default=1)),
                ('addedpokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeadded', to='pokemondatabase.all_pokemon')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.coachdata')),
                ('droppedpokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedropped', to='leagues.roster')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.seasonsetting')),
            ],
        ),
        migrations.AlterField(
            model_name='trade_request',
            name='addedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeaddedrequest', to='leagues.roster'),
        ),
        migrations.AlterField(
            model_name='trade_request',
            name='droppedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedroppedrequest', to='leagues.roster'),
        ),
    ]
