# Generated by Django 2.1.7 on 2019-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0009_auto_20190703_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeagency_announcements',
            name='league_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='replay_announcements',
            name='league_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='trading_announcements',
            name='league_name',
            field=models.CharField(max_length=1000),
        ),
    ]
