# Generated by Django 2.1.7 on 2019-05-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0009_auto_20190521_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='droppedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedropped', to='pokemondatabase.all_pokemon'),
        ),
    ]
