# Generated by Django 2.1.7 on 2019-05-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0010_auto_20190521_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade_request',
            old_name='droppedpokemon',
            new_name='offeredpokemon',
        ),
        migrations.RenameField(
            model_name='trade_request',
            old_name='addedpokemon',
            new_name='requestedpokemon',
        ),
    ]
