# Generated by Django 2.1.7 on 2019-07-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_auto_20190703_1329'),
        ('individualleague', '0010_auto_20190703_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_request',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
