# Generated by Django 2.1.7 on 2019-05-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0011_auto_20190521_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_agency',
            name='droppedpokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped', to='pokemondatabase.all_pokemon'),
        ),
    ]
