# Generated by Django 2.1.7 on 2019-05-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0035_auto_20190523_2037'),
        ('pokemondatabase', '0009_auto_20190517_2045'),
        ('individualleague', '0012_auto_20190522_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='hall_of_fame_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonname', models.CharField(default='Not Specified', max_length=20)),
                ('championteamname', models.CharField(default='Not Specified', max_length=50)),
                ('championcoachname', models.CharField(default='Not Specified', max_length=50)),
                ('runnerupteamname', models.CharField(default='Not Specified', max_length=50)),
                ('runnerupcoachname', models.CharField(default='Not Specified', max_length=50)),
                ('championshipreplay', models.CharField(default='Not Specified', max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='hall_of_fame_roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_of_frame_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hofentries', to='individualleague.hall_of_fame_entry')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
            ],
            options={
                'ordering': ['pokemon__pokemon'],
            },
        ),
    ]
