# Generated by Django 2.1.7 on 2019-07-03 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0012_remove_trade_request_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playoff_match',
            name='season',
        ),
        migrations.RemoveField(
            model_name='playoff_match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='playoff_match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='playoff_match',
            name='winner',
        ),
        migrations.DeleteModel(
            name='playoff_match',
        ),
    ]
