# Generated by Django 2.1.7 on 2019-05-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0013_hall_of_fame_entry_hall_of_fame_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall_of_fame_entry',
            name='champlogo',
            field=models.ImageField(null=True, upload_to='champ_logos'),
        ),
    ]
