# Generated by Django 2.1.7 on 2019-07-04 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0023_auto_20190703_1329'),
        ('individualleague', '0013_auto_20190703_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='pickems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='individualleague.schedule')),
                ('pick', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.coachdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
