# Generated by Django 2.1.7 on 2019-05-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0014_hall_of_fame_entry_champlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_of_fame_entry',
            name='champlogo',
            field=models.ImageField(blank=True, null=True, upload_to='champlogos'),
        ),
    ]
