# Generated by Django 2.1.7 on 2019-05-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0015_auto_20190523_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_of_fame_entry',
            name='seasonname',
            field=models.CharField(default='Not Specified', max_length=30),
        ),
    ]
