# Generated by Django 2.1.7 on 2019-07-15 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individualleague', '0016_auto_20190715_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='winneralternateattribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winneralternateattribution', to=settings.AUTH_USER_MODEL),
        ),
    ]
