# Generated by Django 2.1.7 on 2019-07-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individualleague', '0017_schedule_winneralternateattribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='pickemleaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbercorrect', models.IntegerField(default=0)),
                ('matchescompleted', models.IntegerField(default=0)),
                ('submitted', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
