# Generated by Django 2.1.7 on 2019-07-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0019_auto_20190715_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickems',
            name='submitted',
            field=models.DateField(auto_now=True),
        ),
    ]
