# Generated by Django 2.1.7 on 2019-07-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0020_pickems_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickems',
            name='submitted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
