# Generated by Django 2.1.7 on 2019-10-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0021_auto_20190715_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='replay',
            field=models.CharField(default='Link', max_length=200),
        ),
    ]
