# Generated by Django 2.1.7 on 2019-12-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0022_auto_20191023_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
