# Generated by Django 2.1.7 on 2020-01-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0023_schedule_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_agency',
            name='weekeffective',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='trading',
            name='weekeffective',
            field=models.IntegerField(default='1'),
        ),
    ]
