# Generated by Django 2.2.10 on 2020-10-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0024_auto_20200129_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='team1megaevolved',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='team1usedz',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='team2megaevolved',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='team2usedz',
        ),
        migrations.AddField(
            model_name='schedule',
            name='announced',
            field=models.BooleanField(default=False),
        ),
    ]
