# Generated by Django 2.2.10 on 2020-10-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0025_auto_20201023_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='replay_announcements',
        ),
    ]
