# Generated by Django 2.2.10 on 2020-10-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0026_delete_replay_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_agency',
            name='announced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trading',
            name='announced',
            field=models.BooleanField(default=False),
        ),
    ]
