# Generated by Django 2.1.7 on 2019-05-03 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(blank=True, max_length=30, null=True)),
                ('pfp', models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sitesettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprite', models.CharField(choices=[('xyani.gif', 'XY Animated'), ('xyani-shiny.gif', 'XY Shiny Animated'), ('xyani.png', 'XY'), ('xyani-shiny.png', 'XY Shiny'), ('bw.png', 'BW'), ('bw-shiny.png', 'BW Shiny'), ('afd.png', 'April Fools Day'), ('afd-shiny.png', 'April Fools Day Shiny')], default='xyani.gif', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
