# Generated by Django 2.1.7 on 2019-05-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individualleague', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='traderequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='individualleague.trade_request'),
        ),
    ]
