# Generated by Django 2.1.7 on 2019-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190425_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='defaultpfp.png', null=True, upload_to='profile_pics'),
        ),
    ]
