# Generated by Django 2.1.7 on 2019-06-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190614_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gw',
        ),
    ]
