# Generated by Django 2.1.7 on 2019-04-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190425_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='profile_pics'),
        ),
    ]
