# Generated by Django 2.1.7 on 2019-06-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190617_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discordid',
            field=models.IntegerField(null=True),
        ),
    ]
