# Generated by Django 2.1.7 on 2019-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_inbox_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='messagesubject',
            field=models.TextField(default='Message Subject'),
        ),
    ]
