# Generated by Django 2.1.7 on 2019-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_inbox_messagesubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
