# Generated by Django 2.1.7 on 2019-05-03 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20190425_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitesettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprite', models.CharField(choices=[('xyani.gif', 'XY Animated'), ('xyani-shiny.gif', 'XY Shiny Animated'), ('bwani.gif', 'BW Animated'), ('bwani-shiny.gif', 'BW Shiny')], default='xyani', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
