# Generated by Django 2.1.7 on 2019-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_inbox_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
