# Generated by Django 2.1.7 on 2019-07-03 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190621_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdownalts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showdownalts', to=settings.AUTH_USER_MODEL),
        ),
    ]
