# Generated by Django 2.1.7 on 2019-05-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190521_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='sent',
            new_name='senttime',
        ),
    ]
