# Generated by Django 2.1.7 on 2019-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190503_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='sprite',
            field=models.CharField(choices=[('xyani.gif', 'XY Animated'), ('xyani-shiny.gif', 'XY Shiny Animated'), ('bw.png', 'BW'), ('bw-shiny.png', 'BW Shiny')], default='xyani', max_length=10),
        ),
    ]
