# Generated by Django 2.1.7 on 2019-07-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190703_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seasonsplayed',
            field=models.IntegerField(default=0),
        ),
    ]
