# Generated by Django 2.1.7 on 2019-05-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190521_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='messagetype',
        ),
    ]
