# Generated by Django 2.1.7 on 2019-05-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_inbox_messagetype'),
        ('individualleague', '0008_trade_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='traderequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='individualleague.trade_request'),
        ),
    ]
