# Generated by Django 2.1.7 on 2019-05-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190503_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='sprite',
            field=models.CharField(choices=[('xyani.gif', 'XY Animated'), ('xyani-shiny.gif', 'XY Shiny Animated'), ('xyani.png', 'XY'), ('xyani-shiny.png', 'XY Shiny'), ('bw.png', 'BW'), ('bw-shiny.png', 'BW Shiny'), ('afd.png', 'April Fools Day'), ('afd-shiny.png', 'April Fools Day Shiny')], default='xyani', max_length=10),
        ),
    ]
