# Generated by Django 2.1.7 on 2019-07-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_seasonsplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showdownalts',
            name='showdownalt',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
