# Generated by Django 2.1.7 on 2019-10-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190711_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='damagedone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hphealed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='luck',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='remaininghealth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='support',
            field=models.IntegerField(default=0),
        ),
    ]
