# Generated by Django 2.1.7 on 2019-12-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191024_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='sprite',
            field=models.CharField(choices=[('swsh/ani/standard/.gif', 'Current Animated'), ('swsh/ani/shiny/.gif', 'Current Shiny Animated'), ('swsh/png/standard/.png', 'Current'), ('swsh/png/shiny/.png', 'Current Shiny'), ('bw/png/standard/.png', 'BW'), ('bw/png/shiny/.png', 'BW Shiny'), ('afd/png/standard/.png', 'April Fools Day'), ('afd/png/shiny/.png', 'April Fools Day Shiny')], default='swsh/ani/standard/.gif', max_length=30),
        ),
    ]
