# Generated by Django 2.1.7 on 2020-02-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191214_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='traderequest',
        ),
    ]
