# Generated by Django 2.2.10 on 2020-03-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_coachdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='playoffdifferential',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='playofflosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='playoffwins',
            field=models.IntegerField(default=0),
        ),
    ]
