# Generated by Django 2.2.10 on 2021-02-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200407_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfpurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
