# Generated by Django 2.1.7 on 2019-07-03 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemondatabase', '0003_auto_20190626_0411'),
        ('leagues', '0023_auto_20190703_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicalpokemondraft', to='pokemondatabase.all_pokemon')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='historical_freeagency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedpokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addfa', to='pokemondatabase.all_pokemon')),
                ('droppededpokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropfa', to='pokemondatabase.all_pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='historical_match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=30)),
                ('team1score', models.IntegerField(default=0)),
                ('team2score', models.IntegerField(default=0)),
                ('replay', models.CharField(default='Link', max_length=100)),
                ('team1usedz', models.BooleanField(default=False)),
                ('team2usedz', models.BooleanField(default=False)),
                ('team1megaevolved', models.BooleanField(default=False)),
                ('team2megaevolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='historical_roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('differential', models.IntegerField(default=0)),
                ('gp', models.IntegerField(default=0)),
                ('gw', models.IntegerField(default=0)),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicalpokemonroster', to='pokemondatabase.all_pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='historical_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonname', models.CharField(max_length=100)),
                ('teamname', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, default='league_logos/defaultleaguelogo.png', null=True, upload_to='historic_league_logos')),
                ('coach1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_team_coach1', to=settings.AUTH_USER_MODEL)),
                ('coach2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_team_coach2', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='historical_trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedpokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addtrade', to='pokemondatabase.all_pokemon')),
                ('droppededpokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='droptrade', to='pokemondatabase.all_pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonadmin.historical_team')),
            ],
        ),
        migrations.AddField(
            model_name='historical_roster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonadmin.historical_team'),
        ),
        migrations.AddField(
            model_name='historical_match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historict1', to='pokemonadmin.historical_team'),
        ),
        migrations.AddField(
            model_name='historical_match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historict2', to='pokemonadmin.historical_team'),
        ),
        migrations.AddField(
            model_name='historical_match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicwinner', to='pokemonadmin.historical_team'),
        ),
        migrations.AddField(
            model_name='historical_freeagency',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonadmin.historical_team'),
        ),
        migrations.AddField(
            model_name='historical_draft',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemonadmin.historical_team'),
        ),
    ]
