# Generated by Django 2.1.7 on 2019-07-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicwinner', to='pokemonadmin.historical_team'),
        ),
    ]
