# Generated by Django 2.1.7 on 2019-07-09 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0002_auto_20190703_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_team',
            name='coach1username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='coach2username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historical_team',
            name='coach2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_team_coach2', to=settings.AUTH_USER_MODEL),
        ),
    ]
