# Generated by Django 2.1.7 on 2019-07-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0003_auto_20190709_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_team',
            name='coach1username',
            field=models.CharField(max_length=100),
        ),
    ]
