# Generated by Django 2.1.7 on 2019-07-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0004_auto_20190709_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_team',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
