# Generated by Django 2.1.7 on 2019-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0005_historical_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_draft',
            name='picknumber',
            field=models.IntegerField(default=0),
        ),
    ]
