# Generated by Django 2.1.7 on 2019-07-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0006_historical_draft_picknumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historical_freeagency',
            old_name='droppededpokemon',
            new_name='droppedpokemon',
        ),
    ]
