# Generated by Django 2.1.7 on 2019-07-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0007_auto_20190710_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historical_trading',
            old_name='droppededpokemon',
            new_name='droppedpokemon',
        ),
    ]
