# Generated by Django 2.1.7 on 2019-07-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0008_auto_20190710_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historical_draft',
            options={'ordering': ['picknumber']},
        ),
        migrations.AlterModelOptions(
            name='historical_roster',
            options={'ordering': ['pokemon__pokemon']},
        ),
        migrations.AlterModelOptions(
            name='historical_team',
            options={'ordering': ['-seasonname', 'teamname']},
        ),
        migrations.AlterField(
            model_name='historical_draft',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_draft', to='pokemonadmin.historical_team'),
        ),
        migrations.AlterField(
            model_name='historical_roster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_roster', to='pokemonadmin.historical_team'),
        ),
    ]
