# Generated by Django 2.1.7 on 2019-07-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0009_auto_20190711_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical_team',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='historical_team',
            name='differential',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='forfeit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historical_freeagency',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_freeagency', to='pokemonadmin.historical_team'),
        ),
    ]
