# Generated by Django 2.1.7 on 2019-07-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0010_auto_20190712_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_team',
            name='logo_url',
            field=models.URLField(default=''),
        ),
    ]
