# Generated by Django 2.1.7 on 2019-07-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0011_historical_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_team',
            name='subseason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
