# Generated by Django 2.1.7 on 2019-07-26 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemonadmin', '0012_historical_team_subseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_match',
            name='team1alternateattribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicteam1alternateattribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historical_match',
            name='team2alternateattribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicteam2alternateattribution', to=settings.AUTH_USER_MODEL),
        ),
    ]
