# Generated by Django 2.1.7 on 2019-09-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0014_historical_match_winneralternateattribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_view', models.CharField(max_length=200)),
                ('error_message', models.CharField(max_length=200)),
            ],
        ),
    ]
