# Generated by Django 2.1.7 on 2019-10-14 21:13

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemonadmin', '0015_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_match_replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('week', models.CharField(max_length=30)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicreplayt1', to='pokemonadmin.historical_team')),
                ('team1alternateattribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicreplayteam1alternateattribution', to=settings.AUTH_USER_MODEL)),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicreplayt2', to='pokemonadmin.historical_team')),
                ('team2alternateattribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicreplayteam2alternateattribution', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicreplaywinner', to='pokemonadmin.historical_team')),
                ('winneralternateattribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicreplaywinneralternateattribution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
