# Generated by Django 2.1.7 on 2019-10-22 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0016_historical_match_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical_match_replay',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='historical_match_replay',
            name='team1alternateattribution',
        ),
        migrations.RemoveField(
            model_name='historical_match_replay',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='historical_match_replay',
            name='team2alternateattribution',
        ),
        migrations.RemoveField(
            model_name='historical_match_replay',
            name='week',
        ),
        migrations.RemoveField(
            model_name='historical_match_replay',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='historical_match_replay',
            name='winneralternateattribution',
        ),
        migrations.AddField(
            model_name='historical_match_replay',
            name='match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemonadmin.historical_match'),
        ),
    ]
