# Generated by Django 2.1.7 on 2019-10-22 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0017_auto_20191022_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_match_replay',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokemonadmin.historical_match'),
        ),
    ]
