# Generated by Django 2.1.7 on 2019-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0018_auto_20191022_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_roster',
            name='damagedone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_roster',
            name='hphealed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_roster',
            name='luck',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historical_roster',
            name='remaininghealth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_roster',
            name='support',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='damagedone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='hphealed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='luck',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='remaininghealth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historical_team',
            name='support',
            field=models.IntegerField(default=0),
        ),
    ]
