# Generated by Django 2.2.10 on 2020-03-03 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individualleague', '0024_auto_20200129_0417'),
        ('pokemonadmin', '0019_auto_20191023_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='replaydatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replayuser1', models.CharField(max_length=200)),
                ('replayuser2', models.CharField(max_length=200)),
                ('replay', models.CharField(max_length=500)),
                ('associatedhistoricmatch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemonadmin.historical_match')),
                ('associatedmatch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='individualleague.schedule')),
                ('team1coach1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1coach1', to=settings.AUTH_USER_MODEL)),
                ('team1coach2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1coach2', to=settings.AUTH_USER_MODEL)),
                ('team2coach1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2coach1', to=settings.AUTH_USER_MODEL)),
                ('team2coach2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2coach2', to=settings.AUTH_USER_MODEL)),
                ('winnercoach1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winnercoach1', to=settings.AUTH_USER_MODEL)),
                ('winnercoach2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winnercoach2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
