# Generated by Django 2.2.10 on 2020-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0020_replaydatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaydatabase',
            name='winneruser',
            field=models.CharField(default='', max_length=200),
        ),
    ]
