# Generated by Django 2.2.10 on 2020-03-31 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemonadmin', '0021_replaydatabase_winneruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='favoritereplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_favorited', to='pokemonadmin.replaydatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
