# Generated by Django 2.2.10 on 2020-04-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0022_favoritereplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_team',
            name='subteam',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
