# Generated by Django 2.2.10 on 2020-03-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0023_auto_20200331_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaydatabase',
            name='favorited',
        ),
    ]
