# Generated by Django 2.2.10 on 2020-04-12 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0025_auto_20200406_2347'),
        ('pokemonadmin', '0023_historical_team_subteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='historic_manual_replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1pokemon1kills', models.IntegerField(default=0)),
                ('t1pokemon2kills', models.IntegerField(default=0)),
                ('t1pokemon3kills', models.IntegerField(default=0)),
                ('t1pokemon4kills', models.IntegerField(default=0)),
                ('t1pokemon5kills', models.IntegerField(default=0)),
                ('t1pokemon6kills', models.IntegerField(default=0)),
                ('t2pokemon1kills', models.IntegerField(default=0)),
                ('t2pokemon2kills', models.IntegerField(default=0)),
                ('t2pokemon3kills', models.IntegerField(default=0)),
                ('t2pokemon4kills', models.IntegerField(default=0)),
                ('t2pokemon5kills', models.IntegerField(default=0)),
                ('t2pokemon6kills', models.IntegerField(default=0)),
                ('t1pokemon1death', models.IntegerField(default=0)),
                ('t1pokemon2death', models.IntegerField(default=0)),
                ('t1pokemon3death', models.IntegerField(default=0)),
                ('t1pokemon4death', models.IntegerField(default=0)),
                ('t1pokemon5death', models.IntegerField(default=0)),
                ('t1pokemon6death', models.IntegerField(default=0)),
                ('t2pokemon1death', models.IntegerField(default=0)),
                ('t2pokemon2death', models.IntegerField(default=0)),
                ('t2pokemon3death', models.IntegerField(default=0)),
                ('t2pokemon4death', models.IntegerField(default=0)),
                ('t2pokemon5death', models.IntegerField(default=0)),
                ('t2pokemon6death', models.IntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokemonadmin.historical_match')),
                ('t1pokemon1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam1Pokemon1', to='pokemondatabase.all_pokemon')),
                ('t1pokemon2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam1Pokemon2', to='pokemondatabase.all_pokemon')),
                ('t1pokemon3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam1Pokemon3', to='pokemondatabase.all_pokemon')),
                ('t1pokemon4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam1Pokemon4', to='pokemondatabase.all_pokemon')),
                ('t1pokemon5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam1Pokemon5', to='pokemondatabase.all_pokemon')),
                ('t1pokemon6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam1Pokemon6', to='pokemondatabase.all_pokemon')),
                ('t2pokemon1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam2Pokemon1', to='pokemondatabase.all_pokemon')),
                ('t2pokemon2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam2Pokemon2', to='pokemondatabase.all_pokemon')),
                ('t2pokemon3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam2Pokemon3', to='pokemondatabase.all_pokemon')),
                ('t2pokemon4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam2Pokemon4', to='pokemondatabase.all_pokemon')),
                ('t2pokemon5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam2Pokemon5', to='pokemondatabase.all_pokemon')),
                ('t2pokemon6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistTeam2Pokemon6', to='pokemondatabase.all_pokemon')),
            ],
        ),
    ]
