# Generated by Django 2.2.10 on 2020-03-31 21:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0024_remove_replaydatabase_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaydatabase',
            name='favorited',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=[], size=None),
        ),
    ]
