# Generated by Django 2.2.10 on 2020-04-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0024_historic_manual_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical_match',
            name='team1megaevolved',
        ),
        migrations.RemoveField(
            model_name='historical_match',
            name='team1usedz',
        ),
        migrations.RemoveField(
            model_name='historical_match',
            name='team2megaevolved',
        ),
        migrations.RemoveField(
            model_name='historical_match',
            name='team2usedz',
        ),
    ]
