# Generated by Django 2.2.10 on 2020-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0025_auto_20200420_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_match',
            name='replay',
            field=models.CharField(default='Link', max_length=200),
        ),
    ]
