# Generated by Django 2.2.10 on 2020-08-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0077_auto_20200424_1837'),
        ('pokemonadmin', '0026_auto_20200421_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic_manual_replay',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.coachdata'),
            preserve_default=False,
        ),
    ]
