# Generated by Django 2.2.10 on 2020-08-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0027_historic_manual_replay_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historic_manual_replay',
            name='winner',
        ),
    ]
