# Generated by Django 2.2.10 on 2021-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonadmin', '0028_remove_historic_manual_replay_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_team',
            name='logourl',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
