# Generated by Django 2.2.10 on 2020-03-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draftplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planned_draft',
            name='associatedleague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league_subleague'),
        ),
    ]
