# Generated by Django 2.1.7 on 2019-05-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.CharField(max_length=30, unique=True)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('s_attack', models.IntegerField()),
                ('s_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('is_fully_evolved', models.BooleanField()),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('differential', models.IntegerField(default=0)),
                ('gp', models.IntegerField(default=0)),
                ('gw', models.IntegerField(default=0)),
                ('timesdrafted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='moveinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('move_typing', models.CharField(max_length=10)),
                ('move_category', models.CharField(max_length=10)),
                ('move_power', models.IntegerField()),
                ('move_accuracy', models.IntegerField()),
                ('move_priority', models.IntegerField()),
                ('secondary_effect_chance', models.IntegerField()),
                ('secondary_effect', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pokemon_ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=30)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='pokemon_moveset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.moveinfo')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='pokemon_tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.leaguetiers')),
            ],
        ),
        migrations.CreateModel(
            name='pokemon_tier_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(default='Standard Draft League', max_length=25)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.leaguetiertemplate')),
            ],
        ),
        migrations.CreateModel(
            name='pokemon_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing', models.CharField(max_length=15)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
            ],
        ),
    ]
