# Generated by Django 2.1.7 on 2019-06-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon_moveset',
            options={'ordering': ['moveinfo__name']},
        ),
        migrations.AlterField(
            model_name='pokemon_ability',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='pokemondatabase.all_pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon_moveset',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='pokemondatabase.all_pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon_tier',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_tiers', to='pokemondatabase.all_pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon_type',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='pokemondatabase.all_pokemon'),
        ),
    ]
