# Generated by Django 2.1.7 on 2019-05-03 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_award_coachaward'),
        ('pokemondatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon_tier',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.coachdata'),
        ),
        migrations.AddField(
            model_name='pokemon_tier',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
