# Generated by Django 2.1.7 on 2019-07-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0003_auto_20190626_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon_leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('differential', models.IntegerField(default=0)),
                ('gp', models.IntegerField(default=0)),
                ('gw', models.IntegerField(default=0)),
                ('timesdrafted', models.IntegerField(default=0)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
            ],
        ),
    ]
