# Generated by Django 2.1.7 on 2019-07-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0004_pokemon_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_leaderboard',
            name='pokemon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon'),
        ),
    ]
