# Generated by Django 2.1.7 on 2019-05-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_leaguetiers'),
        ('pokemondatabase', '0004_remove_pokemon_tier_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon_tier',
            name='points',
        ),
        migrations.AddField(
            model_name='pokemon_tier',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.leaguetiers'),
        ),
    ]
