# Generated by Django 2.1.7 on 2019-05-03 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_leaguetiertemplate'),
        ('pokemondatabase', '0005_auto_20190503_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon_tier_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(default='Standard Draft League', max_length=25)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.leaguetiers')),
            ],
        ),
    ]
