# Generated by Django 2.1.7 on 2019-08-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0005_auto_20190715_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon_effectiveness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.IntegerField(default=1)),
                ('dark', models.IntegerField(default=1)),
                ('dragon', models.IntegerField(default=1)),
                ('electric', models.IntegerField(default=1)),
                ('fairy', models.IntegerField(default=1)),
                ('fighting', models.IntegerField(default=1)),
                ('flying', models.IntegerField(default=1)),
                ('ghost', models.IntegerField(default=1)),
                ('grass', models.IntegerField(default=1)),
                ('ground', models.IntegerField(default=1)),
                ('ice', models.IntegerField(default=1)),
                ('normal', models.IntegerField(default=1)),
                ('poison', models.IntegerField(default=1)),
                ('psychic', models.IntegerField(default=1)),
                ('rock', models.IntegerField(default=1)),
                ('steel', models.IntegerField(default=1)),
                ('water', models.IntegerField(default=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
            ],
        ),
    ]
