# Generated by Django 2.1.7 on 2019-08-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0006_pokemon_effectiveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon_effectiveness',
            name='fire',
            field=models.IntegerField(default=1),
        ),
    ]
