# Generated by Django 2.1.7 on 2019-05-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0006_pokemon_tier_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_tier_template',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.leaguetiertemplate'),
        ),
    ]
