# Generated by Django 2.1.7 on 2019-08-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0007_pokemon_effectiveness_fire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='pokemon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness', to='pokemondatabase.all_pokemon'),
        ),
    ]
