# Generated by Django 2.1.7 on 2019-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0007_auto_20190503_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_pokemon',
            name='pokemon',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='moveinfo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
