# Generated by Django 2.1.7 on 2019-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0008_auto_20190504_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_pokemon',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_pokemon',
            name='differential',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_pokemon',
            name='gp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_pokemon',
            name='gw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_pokemon',
            name='kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_pokemon',
            name='timesdrafted',
            field=models.IntegerField(default=0),
        ),
    ]
