# Generated by Django 2.1.7 on 2019-09-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0008_auto_20190830_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='bug',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='dark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='dragon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='electric',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='fairy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='fighting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='fire',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='flying',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='ghost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='grass',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='ground',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='ice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='normal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='poison',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='psychic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='rock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='steel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon_effectiveness',
            name='water',
            field=models.IntegerField(default=0),
        ),
    ]
