# Generated by Django 2.1.7 on 2019-09-11 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0040_auto_20190911_2158'),
        ('pokemondatabase', '0010_all_pokemon_bst'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon_tier',
            name='subleague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subleaguepokemontiers', to='leagues.league_subleague'),
        ),
    ]
