# Generated by Django 2.1.7 on 2019-10-16 13:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0011_pokemon_tier_subleague'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_pokemon',
            name='nicknames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=[], size=None),
            preserve_default=False,
        ),
    ]
