# Generated by Django 2.1.7 on 2019-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0013_auto_20191023_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_pokemon',
            name='gen8',
            field=models.BooleanField(default=False),
        ),
    ]
