# Generated by Django 2.1.7 on 2019-11-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0014_all_pokemon_gen8'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon_tier',
            options={'ordering': ['pokemon__pokemon']},
        ),
        migrations.AlterModelOptions(
            name='pokemon_tier_template',
            options={'ordering': ['pokemon__pokemon']},
        ),
        migrations.AlterField(
            model_name='pokemon_tier_template',
            name='template',
            field=models.CharField(default='Standard Draft League', max_length=50),
        ),
    ]
