# Generated by Django 2.1.7 on 2020-01-14 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0059_auto_20200114_0243'),
        ('pokemondatabase', '0015_auto_20191123_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon_tier',
            name='rosterspot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.roster'),
        ),
    ]
