# Generated by Django 2.1.7 on 2020-02-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0016_pokemon_tier_rosterspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon_sprites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afd', models.ImageField(default='sprites/sprites_placeholder.gif', upload_to='sprites/afd/png/standard')),
                ('bw', models.ImageField(default='sprites/sprites_placeholder.gif', upload_to='sprites/bw/png/standard')),
                ('dex', models.ImageField(default='sprites/sprites_placeholder.gif', upload_to='sprites/dex/png/standard')),
                ('afdshiny', models.ImageField(default='sprites/sprites_placeholder.gif', upload_to='sprites/afd/png/shiny')),
                ('bwshiny', models.ImageField(default='sprites/sprites_placeholder.gif', upload_to='sprites/bw/png/shiny')),
                ('dexshiny', models.ImageField(default='sprites/sprites_placeholder.gif', upload_to='sprites/dex/png/shiny')),
                ('dexani', models.ImageField(default='sprites/sprites_placeholder.gif', upload_to='sprites/dex/ani/standard')),
                ('dexanishiny', models.ImageField(default='sprites/sprites_placeholder.gif', upload_to='sprites/dex/ani/shiny')),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
            ],
        ),
    ]
