# Generated by Django 2.1.7 on 2020-02-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0017_pokemon_sprites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='afd',
            field=models.ImageField(default='sprites/sprite_placeholder.gif', upload_to='sprites/afd/png/standard'),
        ),
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='afdshiny',
            field=models.ImageField(default='sprites/sprite_placeholder.gif', upload_to='sprites/afd/png/shiny'),
        ),
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='bw',
            field=models.ImageField(default='sprites/sprite_placeholder.gif', upload_to='sprites/bw/png/standard'),
        ),
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='bwshiny',
            field=models.ImageField(default='sprites/sprite_placeholder.gif', upload_to='sprites/bw/png/shiny'),
        ),
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='dex',
            field=models.ImageField(default='sprites/sprite_placeholder.gif', upload_to='sprites/dex/png/standard'),
        ),
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='dexani',
            field=models.ImageField(default='sprites/sprite_placeholder.gif', upload_to='sprites/dex/ani/standard'),
        ),
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='dexanishiny',
            field=models.ImageField(default='sprites/sprite_placeholder.gif', upload_to='sprites/dex/ani/shiny'),
        ),
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='dexshiny',
            field=models.ImageField(default='sprites/sprite_placeholder.gif', upload_to='sprites/dex/png/shiny'),
        ),
        migrations.AlterField(
            model_name='pokemon_sprites',
            name='pokemon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprite', to='pokemondatabase.all_pokemon'),
        ),
    ]
