# Generated by Django 2.2.10 on 2020-03-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0018_auto_20200211_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_pokemon',
            options={'ordering': ['pokemon']},
        ),
    ]
