# Generated by Django 2.2.10 on 2020-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0019_auto_20200303_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveinfo',
            name='altname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
