# Generated by Django 2.2.10 on 2020-03-27 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0021_all_pokemon_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='preevolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
                ('preevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevos', to='pokemondatabase.all_pokemon')),
            ],
        ),
    ]
