# Generated by Django 2.2.10 on 2020-04-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0073_auto_20200317_2052'),
        ('pokemondatabase', '0022_preevolution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemon_tier',
            unique_together={('pokemon', 'subleague')},
        ),
    ]
