# Generated by Django 2.2.10 on 2020-04-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0023_auto_20200402_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemon_moveset',
            unique_together={('pokemon', 'moveinfo')},
        ),
    ]
