# Generated by Django 2.2.10 on 2020-04-06 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0024_auto_20200403_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon_tier',
            name='rosterspot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.roster'),
        ),
        migrations.AlterField(
            model_name='pokemon_tier',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.leaguetiers'),
        ),
        migrations.AlterField(
            model_name='pokemon_tier_template',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.leaguetiertemplate'),
        ),
    ]
