# Generated by Django 2.2.10 on 2020-06-17 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemondatabase', '0027_pokemon_movedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_movedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('crits', models.IntegerField(default=0)),
                ('posssecondaryeffects', models.IntegerField(default=0)),
                ('secondaryeffects', models.IntegerField(default=0)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moveinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.moveinfo')),
            ],
        ),
    ]
