# Generated by Django 2.2.10 on 2020-06-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0028_user_movedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_pokemon',
            name='candynamax',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='all_pokemon',
            name='canzmove',
            field=models.BooleanField(default=True),
        ),
    ]
