# Generated by Django 2.2.10 on 2020-06-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0029_auto_20200617_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='unmatched_moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.CharField(max_length=300, unique=True)),
                ('moveinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.moveinfo')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon')),
            ],
        ),
    ]
