# Generated by Django 2.2.10 on 2020-06-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0031_moveinfo_move_crit_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemon_type',
            unique_together={('pokemon', 'typing')},
        ),
    ]
