# Generated by Django 2.2.10 on 2020-06-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0032_auto_20200618_1916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemon_ability',
            unique_together={('pokemon', 'ability')},
        ),
    ]
