# Generated by Django 2.2.10 on 2020-06-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0035_auto_20200619_1710'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unmatched_moves',
            unique_together={('pokemon', 'moveinfo')},
        ),
    ]
