# Generated by Django 2.2.10 on 2020-10-24 05:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0037_auto_20200620_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_pokemon',
            name='nicknames',
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='bst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='is_fully_evolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='s_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='s_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_pokemon',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
