# Generated by Django 2.2.10 on 2020-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemondatabase', '0038_auto_20201023_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_pokemon',
            name='gen8',
            field=models.BooleanField(default=True),
        ),
    ]
