# Generated by Django 2.1.7 on 2019-05-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individualleague', '0001_initial'),
        ('pokemondatabase', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manual_replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.CharField(default='None', max_length=200)),
                ('t1megaevolved', models.BooleanField(default='False')),
                ('t2megaevolved', models.BooleanField(default='False')),
                ('t1usedz', models.BooleanField(default='False')),
                ('t2usedz', models.BooleanField(default='False')),
                ('t1pokemon1kills', models.IntegerField(default=0)),
                ('t1pokemon2kills', models.IntegerField(default=0)),
                ('t1pokemon3kills', models.IntegerField(default=0)),
                ('t1pokemon4kills', models.IntegerField(default=0)),
                ('t1pokemon5kills', models.IntegerField(default=0)),
                ('t1pokemon6kills', models.IntegerField(default=0)),
                ('t2pokemon1kills', models.IntegerField(default=0)),
                ('t2pokemon2kills', models.IntegerField(default=0)),
                ('t2pokemon3kills', models.IntegerField(default=0)),
                ('t2pokemon4kills', models.IntegerField(default=0)),
                ('t2pokemon5kills', models.IntegerField(default=0)),
                ('t2pokemon6kills', models.IntegerField(default=0)),
                ('t1pokemon1death', models.IntegerField(default=0)),
                ('t1pokemon2death', models.IntegerField(default=0)),
                ('t1pokemon3death', models.IntegerField(default=0)),
                ('t1pokemon4death', models.IntegerField(default=0)),
                ('t1pokemon5death', models.IntegerField(default=0)),
                ('t1pokemon6death', models.IntegerField(default=0)),
                ('t2pokemon1death', models.IntegerField(default=0)),
                ('t2pokemon2death', models.IntegerField(default=0)),
                ('t2pokemon3death', models.IntegerField(default=0)),
                ('t2pokemon4death', models.IntegerField(default=0)),
                ('t2pokemon5death', models.IntegerField(default=0)),
                ('t2pokemon6death', models.IntegerField(default=0)),
                ('t1forfeit', models.BooleanField(default='False')),
                ('t2forfeit', models.BooleanField(default='False')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individualleague.schedule')),
                ('t1pokemon1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1Pokemon1', to='pokemondatabase.all_pokemon')),
                ('t1pokemon2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1Pokemon2', to='pokemondatabase.all_pokemon')),
                ('t1pokemon3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1Pokemon3', to='pokemondatabase.all_pokemon')),
                ('t1pokemon4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1Pokemon4', to='pokemondatabase.all_pokemon')),
                ('t1pokemon5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1Pokemon5', to='pokemondatabase.all_pokemon')),
                ('t1pokemon6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1Pokemon6', to='pokemondatabase.all_pokemon')),
                ('t2pokemon1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2Pokemon1', to='pokemondatabase.all_pokemon')),
                ('t2pokemon2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2Pokemon2', to='pokemondatabase.all_pokemon')),
                ('t2pokemon3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2Pokemon3', to='pokemondatabase.all_pokemon')),
                ('t2pokemon4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2Pokemon4', to='pokemondatabase.all_pokemon')),
                ('t2pokemon5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2Pokemon5', to='pokemondatabase.all_pokemon')),
                ('t2pokemon6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2Pokemon6', to='pokemondatabase.all_pokemon')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.coachdata')),
            ],
        ),
    ]
