# Generated by Django 2.1.7 on 2019-10-14 21:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individualleague', '0021_auto_20190715_2207'),
        ('replayanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individualleague.schedule')),
            ],
        ),
    ]
