# Generated by Django 2.1.7 on 2019-10-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replayanalysis', '0002_match_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_replay',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='individualleague.schedule'),
        ),
    ]
