# Generated by Django 2.1.7 on 2019-10-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replayanalysis', '0003_auto_20191016_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual_replay',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='individualleague.schedule'),
        ),
    ]
