# Generated by Django 2.1.7 on 2020-01-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replayanalysis', '0004_auto_20191023_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual_replay',
            name='match',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t1pokemon1',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t1pokemon2',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t1pokemon3',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t1pokemon4',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t1pokemon5',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t1pokemon6',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t2pokemon1',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t2pokemon2',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t2pokemon3',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t2pokemon4',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t2pokemon5',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='t2pokemon6',
        ),
        migrations.RemoveField(
            model_name='manual_replay',
            name='winner',
        ),
        migrations.DeleteModel(
            name='manual_replay',
        ),
    ]
