# Generated by Django 2.2.10 on 2020-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replayanalysis', '0007_auto_20200411_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='failed_replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
