# Generated by Django 2.1.7 on 2019-05-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardname', models.CharField(default='None', max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='awards')),
            ],
        ),
        migrations.CreateModel(
            name='coachaward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='coachdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='team_logos')),
                ('teamabbreviation', models.CharField(default='TBD', max_length=3)),
                ('teamname', models.CharField(default='To Be Determined', max_length=100)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('differential', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('forfeit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='conference_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='division_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picktime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='league',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('logo', models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='league_logos')),
            ],
        ),
        migrations.CreateModel(
            name='league_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='league_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_teams', models.IntegerField(default=16)),
                ('number_of_conferences', models.IntegerField(default=2)),
                ('number_of_divisions', models.IntegerField(default=2)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('allows_teams', models.BooleanField(default=False)),
                ('teambased', models.BooleanField(default=False)),
                ('discordurl', models.CharField(default='Not Provided', max_length=100)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='leaguetiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiername', models.CharField(default='Not Specified', max_length=20)),
                ('tierpoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='leaguetiertemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(default='Standard Draft League', max_length=25)),
                ('tiername', models.CharField(default='Not Specified', max_length=20)),
                ('tierpoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('differential', models.IntegerField(default=0)),
                ('gp', models.IntegerField(default=0)),
                ('gw', models.IntegerField(default=0)),
                ('zuser', models.CharField(choices=[('OS', 'Offensive and Status'), ('O', 'Offensive'), ('N', 'None')], default='N', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='seasonsetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonname', models.CharField(default='Season 1', max_length=25)),
                ('draftstart', models.DateTimeField(null=True)),
                ('drafttimer', models.IntegerField(default=12)),
                ('draftbudget', models.IntegerField(default=1080)),
                ('picksperteam', models.IntegerField(default=12)),
                ('drafttype', models.CharField(choices=[('Snake', 'Snake')], default='Snake', max_length=25)),
                ('seasonstart', models.DateTimeField(null=True)),
                ('seasonlength', models.IntegerField(default=7)),
                ('freeagenciesallowed', models.IntegerField(default=4)),
                ('tradesallowed', models.IntegerField(default=4)),
                ('numzusers', models.IntegerField(default=2)),
                ('candeletez', models.BooleanField(default=False)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
    ]
