# Generated by Django 2.1.7 on 2019-05-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coachdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='team_logos')),
                ('teamabbreviation', models.CharField(default='TBD', max_length=3)),
                ('teamname', models.CharField(default='To Be Determined', max_length=100)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='league',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='league_logos')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='league_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('league_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='league_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_teams', models.IntegerField(default=16)),
                ('number_of_conferences', models.IntegerField(default=2)),
                ('number_of_divisions', models.IntegerField(default=2)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('discordurl', models.CharField(default='Not Provided', max_length=100)),
                ('league_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
        migrations.AddField(
            model_name='coachdata',
            name='league_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
