# Generated by Django 2.1.7 on 2019-05-01 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='league_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_teams', models.IntegerField(default=16)),
                ('number_of_conferences', models.IntegerField(default=2)),
                ('number_of_divisions', models.IntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='league_logos'),
        ),
        migrations.AddField(
            model_name='league_settings',
            name='league_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
