# Generated by Django 2.1.7 on 2019-05-31 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20190531_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='league_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Specified', max_length=50)),
                ('logo', models.ImageField(blank=True, default='profile_pics/defaultpfp.png', null=True, upload_to='team_logos')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagueteam', to='leagues.league')),
            ],
        ),
        migrations.AddField(
            model_name='coachdata',
            name='parent_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.league_team'),
        ),
    ]
