# Generated by Django 2.1.7 on 2019-05-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20190501_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_settings',
            name='is_recruiting',
            field=models.BooleanField(default=True),
        ),
    ]
