# Generated by Django 2.1.7 on 2019-05-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_leaguetiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaguetiertemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(default='Standard Draft League', max_length=25)),
                ('tiername', models.CharField(default='Not Specified', max_length=20)),
                ('tierpoints', models.IntegerField(default=0)),
            ],
        ),
    ]
