# Generated by Django 2.1.7 on 2019-05-04 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0004_leaguetiertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdata',
            name='teammate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teammate', to=settings.AUTH_USER_MODEL),
        ),
    ]
