# Generated by Django 2.1.7 on 2019-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_coachdata_teammate'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_settings',
            name='allows_teams',
            field=models.BooleanField(default=False),
        ),
    ]
