# Generated by Django 2.1.7 on 2019-05-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_league_settings_allows_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_settings',
            name='draftbudget',
            field=models.IntegerField(default=1000),
        ),
    ]
