# Generated by Django 2.1.7 on 2019-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20190618_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_team',
            name='differential',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league_team',
            name='gp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league_team',
            name='gw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league_team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league_team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league_team',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league_team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
