# Generated by Django 2.1.7 on 2019-05-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20190504_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasonsetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draftbudget', models.IntegerField(default=1080)),
                ('picksperteam', models.IntegerField(default=12)),
                ('seasonlength', models.IntegerField(default=7)),
                ('freeagenciesallowed', models.IntegerField(default=4)),
                ('tradesallowed', models.IntegerField(default=4)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
        migrations.RemoveField(
            model_name='league_settings',
            name='draftbudget',
        ),
    ]
