# Generated by Django 2.1.7 on 2019-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_league_settings_discordserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='draft_announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
