# Generated by Django 2.1.7 on 2019-06-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_draft_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_announcements',
            name='announced',
            field=models.BooleanField(default=False),
        ),
    ]
