# Generated by Django 2.1.7 on 2019-06-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_draft_announcements_announced'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_announcements',
            name='league_name',
            field=models.CharField(default='All%20Star%20Premier%20League', max_length=100),
            preserve_default=False,
        ),
    ]
