# Generated by Django 2.1.7 on 2019-05-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_draft_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemondatabase.all_pokemon'),
        ),
    ]
