# Generated by Django 2.1.7 on 2019-06-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_draft_announcements_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_announcements',
            name='upnext',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
