# Generated by Django 2.1.7 on 2019-05-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_auto_20190505_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsetting',
            name='drafttype',
            field=models.CharField(choices=[('Snake', 'Snake')], default='Snake', max_length=25),
        ),
    ]
