# Generated by Django 2.1.7 on 2019-05-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_auto_20190505_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='pickstart',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
