# Generated by Django 2.1.7 on 2019-05-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_draft_pickstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdata',
            name='conferencenumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coachdata',
            name='divisionnumber',
            field=models.IntegerField(default=1),
        ),
    ]
