# Generated by Django 2.1.7 on 2019-06-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_auto_20190621_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_settings',
            name='replaychannel',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
