# Generated by Django 2.1.7 on 2019-06-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0017_discord_settings_replaychannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_announcements',
            name='draftchannel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
