# Generated by Django 2.1.7 on 2019-05-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0017_conference_name_division_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachdata',
            name='conferencenumber',
        ),
        migrations.RemoveField(
            model_name='coachdata',
            name='divisionnumber',
        ),
        migrations.AddField(
            model_name='division_name',
            name='associatedconference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.conference_name'),
        ),
    ]
