# Generated by Django 2.1.7 on 2019-06-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_draft_announcements_draftchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_announcements',
            name='upnextid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
