# Generated by Django 2.1.7 on 2019-05-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_auto_20190509_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division_name',
            name='associatedconference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.conference_name'),
        ),
    ]
