# Generated by Django 2.1.7 on 2019-06-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_draft_announcements_upnextid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetiers',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaguetiers', to='leagues.league'),
        ),
    ]
