# Generated by Django 2.1.7 on 2019-06-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0020_auto_20190626_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
