# Generated by Django 2.1.7 on 2019-05-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0020_auto_20190509_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdata',
            name='differential',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachdata',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachdata',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachdata',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
