# Generated by Django 2.1.7 on 2019-06-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0021_draft_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsetting',
            name='playoffslength',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemonroster', to='pokemondatabase.all_pokemon'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamroster', to='leagues.coachdata'),
        ),
    ]
