# Generated by Django 2.1.7 on 2019-05-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0022_coachdata_forfeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='zuser',
            field=models.CharField(choices=[('OS', 'Offensive and Status'), ('O', 'Offensive'), ('N', 'None')], default='N', max_length=20),
        ),
    ]
