# Generated by Django 2.1.7 on 2019-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_roster_zuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsetting',
            name='numzusers',
            field=models.IntegerField(default=2),
        ),
    ]
