# Generated by Django 2.1.7 on 2019-07-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_auto_20190703_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachaward',
            name='text',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
