# Generated by Django 2.1.7 on 2019-07-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0024_coachaward_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachaward',
            options={'ordering': ['award__id']},
        ),
        migrations.AddField(
            model_name='award',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
