# Generated by Django 2.1.7 on 2019-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0025_roster_candeletez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='candeletez',
        ),
        migrations.AddField(
            model_name='seasonsetting',
            name='candeletez',
            field=models.BooleanField(default=False),
        ),
    ]
