# Generated by Django 2.1.7 on 2019-07-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0026_auto_20190714_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='awardname',
            field=models.CharField(default='None', max_length=50, unique=True),
        ),
    ]
