# Generated by Django 2.1.7 on 2019-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0026_auto_20190515_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsetting',
            name='seasonstart',
            field=models.DateTimeField(null=True),
        ),
    ]
