# Generated by Django 2.1.7 on 2019-05-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0027_seasonsetting_seasonstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_settings',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
