# Generated by Django 2.1.7 on 2019-07-14 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0027_auto_20190714_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachaward',
            options={'ordering': ['award__ordering', '-text']},
        ),
        migrations.RemoveField(
            model_name='league',
            name='host',
        ),
        migrations.AddField(
            model_name='league',
            name='host',
            field=models.ManyToManyField(related_name='hosting', to=settings.AUTH_USER_MODEL),
        ),
    ]
