# Generated by Django 2.1.7 on 2019-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0028_league_settings_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsetting',
            name='draftstart',
            field=models.DateTimeField(null=True),
        ),
    ]
