# Generated by Django 2.1.7 on 2019-07-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0028_auto_20190714_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemondraft', to='pokemondatabase.all_pokemon'),
        ),
    ]
