# Generated by Django 2.1.7 on 2019-05-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0029_seasonsetting_draftstart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='pickstart',
        ),
        migrations.AddField(
            model_name='draft',
            name='picktime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
