# Generated by Django 2.1.7 on 2019-07-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0029_auto_20190715_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachaward',
            name='timeawarded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
