# Generated by Django 2.1.7 on 2019-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0030_coachaward_timeawarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachaward',
            name='timeawarded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
