# Generated by Django 2.1.7 on 2019-05-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0030_auto_20190520_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsetting',
            name='drafttimer',
            field=models.IntegerField(default=12),
        ),
    ]
