# Generated by Django 2.1.7 on 2019-09-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0031_auto_20190726_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_application',
            name='discord_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='league_application',
            name='draft_league_resume',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='league_application',
            name='tier_preference',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
