# Generated by Django 2.1.7 on 2019-09-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0032_auto_20190909_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_settings',
            name='discordserver',
        ),
        migrations.RemoveField(
            model_name='league_settings',
            name='discordurl',
        ),
        migrations.AddField(
            model_name='discord_settings',
            name='discordserver',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='discord_settings',
            name='discordurl',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
