# Generated by Django 2.1.7 on 2019-05-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0032_hall_of_fame_entry_hall_of_fame_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall_of_fame_entry',
            name='championcoachname',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='hall_of_fame_entry',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
        migrations.AddField(
            model_name='hall_of_fame_entry',
            name='runnerupcoachname',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
