# Generated by Django 2.1.7 on 2019-05-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0033_auto_20190523_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_of_fame_entry',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
