# Generated by Django 2.1.7 on 2019-09-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0033_auto_20190909_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='league_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_subleagues', models.IntegerField(default=1)),
                ('number_of_teams_per_league', models.IntegerField(default=16)),
                ('number_of_conferences_per_league', models.IntegerField(default=2)),
                ('number_of_divisions_per_league', models.IntegerField(default=2)),
                ('allows_teams', models.BooleanField(default=False)),
                ('teambased', models.BooleanField(default=False)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='leagues.league')),
            ],
        ),
    ]
