# Generated by Django 2.1.7 on 2019-05-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0034_auto_20190523_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall_of_fame_entry',
            name='league',
        ),
        migrations.RemoveField(
            model_name='hall_of_fame_roster',
            name='hall_of_frame_entry',
        ),
        migrations.RemoveField(
            model_name='hall_of_fame_roster',
            name='pokemon',
        ),
        migrations.DeleteModel(
            name='hall_of_fame_entry',
        ),
        migrations.DeleteModel(
            name='hall_of_fame_roster',
        ),
    ]
