# Generated by Django 2.1.7 on 2019-09-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0035_league_subleague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_subleague',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subleague', to='leagues.league'),
        ),
    ]
