# Generated by Django 2.1.7 on 2019-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0035_auto_20190523_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdata',
            name='parent_team',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='league_settings',
            name='teambased',
            field=models.BooleanField(default=False),
        ),
    ]
