# Generated by Django 2.1.7 on 2019-09-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0036_auto_20190909_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league_team',
            old_name='alternate',
            new_name='captain',
        ),
    ]
