# Generated by Django 2.1.7 on 2019-09-11 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0039_auto_20190909_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdata',
            name='league_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagueteams', to='leagues.league'),
        ),
    ]
