# Generated by Django 2.1.7 on 2019-09-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0041_auto_20190911_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonsetting',
            name='subleague',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.league_subleague'),
        ),
    ]
