# Generated by Django 2.1.7 on 2019-09-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0042_auto_20190913_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdata',
            name='subleague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subleague_coachs', to='leagues.league_subleague'),
        ),
        migrations.AlterField(
            model_name='seasonsetting',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='seasonsetting',
            name='subleague',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league_subleague'),
        ),
    ]
