# Generated by Django 2.1.7 on 2019-09-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0043_auto_20190916_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_settings',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_settings', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='discord_settings',
            name='subleague',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.league_subleague'),
        ),
    ]
