# Generated by Django 2.1.7 on 2019-09-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0044_auto_20190916_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_application',
            name='tier_preference',
        ),
        migrations.AddField(
            model_name='league_application',
            name='tier_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apptiers', to='leagues.league_subleague'),
        ),
    ]
