# Generated by Django 2.1.7 on 2019-09-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0045_auto_20190916_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_application',
            name='tier_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apptiers', to='leagues.league_subleague'),
        ),
    ]
