# Generated by Django 2.1.7 on 2019-09-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0046_auto_20190916_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_application',
            name='tier_preference',
        ),
        migrations.AddField(
            model_name='league_application',
            name='tier_preference',
            field=models.ManyToManyField(related_name='apptiers', to='leagues.league_subleague'),
        ),
    ]
