# Generated by Django 2.1.7 on 2019-09-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0047_auto_20190916_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_application',
            name='teamabbreviation',
            field=models.CharField(default='TBD', max_length=3),
        ),
        migrations.AddField(
            model_name='league_application',
            name='teamname',
            field=models.CharField(default='To Be Determined', max_length=100),
        ),
    ]
