# Generated by Django 2.1.7 on 2019-09-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0048_auto_20190917_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetiers',
            name='subleague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subleaguetiers', to='leagues.league_subleague'),
        ),
    ]
