# Generated by Django 2.1.7 on 2019-09-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0049_auto_20190923_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsetting',
            name='number_of_conferences',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='seasonsetting',
            name='number_of_divisions',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='seasonsetting',
            name='number_of_teams',
            field=models.IntegerField(default=16),
        ),
    ]
