# Generated by Django 2.1.7 on 2019-10-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0050_auto_20190923_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_team',
            name='shortname',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
