# Generated by Django 2.1.7 on 2019-10-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0051_league_team_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='damagedone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='hphealed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='luck',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='roster',
            name='remaininghealth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roster',
            name='support',
            field=models.IntegerField(default=0),
        ),
    ]
