# Generated by Django 2.1.7 on 2019-10-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0052_auto_20191015_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='luck',
            field=models.FloatField(default=0),
        ),
    ]
