# Generated by Django 2.1.7 on 2019-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0053_auto_20191016_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdata',
            name='damagedone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachdata',
            name='hphealed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachdata',
            name='luck',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coachdata',
            name='remaininghealth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachdata',
            name='support',
            field=models.IntegerField(default=0),
        ),
    ]
