# Generated by Django 2.1.7 on 2019-12-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0055_auto_20191129_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_settings',
            name='number_of_conferences',
        ),
        migrations.RemoveField(
            model_name='league_settings',
            name='number_of_divisions',
        ),
        migrations.RemoveField(
            model_name='league_settings',
            name='number_of_teams',
        ),
    ]
