# Generated by Django 2.1.7 on 2019-12-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0056_auto_20191212_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_configuration',
            name='number_of_teams_per_league',
        ),
    ]
