# Generated by Django 2.1.7 on 2019-12-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0057_remove_league_configuration_number_of_teams_per_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_configuration',
            name='number_of_conferences_per_league',
        ),
        migrations.RemoveField(
            model_name='league_configuration',
            name='number_of_divisions_per_league',
        ),
    ]
