# Generated by Django 2.1.7 on 2020-01-14 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0058_auto_20191212_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguetiers',
            options={'ordering': ['league']},
        ),
        migrations.AlterField(
            model_name='leaguetiers',
            name='subleague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subleaguetiers', to='leagues.league_subleague'),
        ),
    ]
