# Generated by Django 2.1.7 on 2020-01-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0059_auto_20200114_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='picknumber',
            field=models.IntegerField(default=0),
        ),
    ]
