# Generated by Django 2.1.7 on 2020-01-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0060_draft_picknumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_application',
            name='willingtobealternate',
            field=models.BooleanField(default=True),
        ),
    ]
