# Generated by Django 2.1.7 on 2020-01-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0061_league_application_willingtobealternate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_settings',
            name='allows_teams',
        ),
        migrations.RemoveField(
            model_name='league_settings',
            name='teambased',
        ),
    ]
