# Generated by Django 2.1.7 on 2020-01-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0063_auto_20200128_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference_name',
            name='subleague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subleague_conferences', to='leagues.league_subleague'),
        ),
    ]
