# Generated by Django 2.1.7 on 2020-01-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0065_auto_20200128_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division_name',
            name='subleague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league_subleague'),
        ),
    ]
