# Generated by Django 2.1.7 on 2020-01-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0066_auto_20200128_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdata',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferenceteams', to='leagues.conference_name'),
        ),
        migrations.AlterField(
            model_name='coachdata',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisionteams', to='leagues.division_name'),
        ),
    ]
