# Generated by Django 2.2.10 on 2020-03-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0069_auto_20200303_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
