# Generated by Django 2.2.10 on 2020-03-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0070_league_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
