# Generated by Django 2.2.10 on 2020-04-07 20:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0073_auto_20200317_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coachaward',
            unique_together={('coach', 'award', 'text')},
        ),
    ]
