# Generated by Django 2.2.10 on 2020-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0074_auto_20200407_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_settings',
            name='platform',
            field=models.CharField(choices=[('Youtube Showdown', 'Youtube Showdown'), ('Youtube Wifi', 'Youtube Wifi'), ('Showdown', 'Showdown'), ('Wifi', 'Wifi')], default='Showdown', max_length=30),
        ),
    ]
