# Generated by Django 2.2.10 on 2020-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0076_league_configuration_allows_cross_subleague_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_announcements',
            name='imageurl',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='draft_announcements',
            name='subleague',
            field=models.CharField(default='Main', max_length=100),
        ),
    ]
