# Generated by Django 2.2.10 on 2020-10-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0079_draft_announced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='draft_announcements',
        ),
    ]
