# Generated by Django 2.2.10 on 2021-02-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0081_auto_20210210_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_team',
            name='logourl',
            field=models.URLField(blank=True, default='https://i.imgur.com/buHiZ1x.png', max_length=400),
        ),
        migrations.AddField(
            model_name='teamlogo',
            name='logourl',
            field=models.URLField(blank=True, default='https://i.imgur.com/buHiZ1x.png', max_length=400),
        ),
        migrations.AlterField(
            model_name='coachdata',
            name='logourl',
            field=models.URLField(blank=True, default='https://i.imgur.com/buHiZ1x.png', max_length=400),
        ),
    ]
